# Generated by Django 5.2.7 on 2025-10-26 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100)),
                ('pretensao_salarial', models.IntegerField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 a 2.000'), (3, 'De 2.000 a 3.000'), (4, 'Acima de 3.000')])),
                ('experiencia', models.TextField()),
                ('ultima_escolaridade', models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('faixa_salarial', models.IntegerField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 a 2.000'), (3, 'De 2.000 a 3.000'), (4, 'Acima de 3.000')])),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')])),
                ('candidatos', models.ManyToManyField(related_name='vagas_aplicadas', to='sitevagas.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='sitevagas.empresa')),
            ],
        ),
    ]
