# Generated by Django 5.2.7 on 2025-10-28 00:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevagas', '0002_vaga_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
