# Generated by Django 5.2.7 on 2025-10-28 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevagas', '0003_rename_created_at_vaga_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='candidatos',
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pontuacao', models.IntegerField(default=0)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_candidaturas', to='sitevagas.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_recebidas', to='sitevagas.vaga')),
            ],
            options={
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['data_aplicacao'],
                'unique_together': {('vaga', 'candidato')},
            },
        ),
    ]
