# Generated by Django 5.2.7 on 2025-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevagas', '0004_remove_candidato_data_criacao_remove_vaga_candidatos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='candidatos',
            field=models.ManyToManyField(blank=True, related_name='vagas_aplicadas', through='sitevagas.Candidatura', to='sitevagas.candidato'),
        ),
    ]
