# Generated by Django 5.2.1 on 2025-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitevagas', '0005_vaga_candidatos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
